export const Images = {
    logo:require('./Png/logo.png'),
    exercise:require('./Png/exercise.png'),
    track:require('./Png/track.png'),
    health:require('./Png/health.png'),
    yellowblob:require('./Png/yellowblob.png'),
    pinkblob:require('./Png/pinkblob.png'),
    blueblob: require('./Png/blueblob.png'),
    signup: require('./Png/signup.png'),
    introbubble: require('./Png/introbubble.png'),
    intoimg: require('./Png/introimg.png'),
    backabutton: require('./Png/back.png'),
    heart: require('./Png/Heart.png'),
    flag: require('./Png/Flag.png'),
    lol: require('./Png/LOL.png'),
    bot: require('./Png/Chatbot.png'),
    tasks: require('./Png/Tasks.png'),
    male: require('./Png/male.png'),
    female: require('./Png/female.png'),
    maleIcon: require('./Png/MaleIcon.png'),
    femaleIcon: require('./Png/FemaleIcon.png'),
    doctor: require('./Png/doctor.png'),
    happy: require('./Png/happy.png'),
    sad: require('./Png/sad.png'),
    docpres: require('./Png/docpres.png'),
    nomed: require('./Png/nomed.png'),
    pill: require('./Png/Pill.png'),
    unavailable: require('./Png/unavailable.png'),
    home: require('./Png/Home.png'),
    recc: require('./Png/Recc.png'),
    community: require('./Png/Chat.png'),
    profile: require('./Png/profile.png'),
    left: require('./Png/Left.png'),
    customer: require('./Png/Customer.png'),
    plus: require('./Png/plus.png'),
    cup: require('./Png/cup.png'),
    flame: require('./Png/flame.png'),
    moon: require('./Png/moon.png'),
    star: require('./Png/star.png'),
    starcolor: require('./Png/starcolor.png'),
    depressed: require('./Png/depressed.png'),
    anxious: require('./Png/anxious.png'),
    doubtful: require('./Png/doubtful.png'),
    happy1: require('./Png/happy1.png'),
    joyful: require('./Png/joyful.png'),
    normal : require('./Png/normal.png'),
    loader: require('./Png/loader.png'),
    play: require('./Png/Play.png'),
    replay :require('./Png/replay.png'),
    forward : require('./Png/forward.png'),
    communityicon: require('./Png/community.png'),
    sent: require('./Png/Sent.png'),
    nature:require('./Png/Nature.png'),
    maleprofile: require('./Png/maleprofile.png'),
    femaleprofile: require('./Png/femaleprofile.png')

}