import { StyleSheet } from "react-native";
import { Colors } from "../../res/Colors";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:Colors.quesBackground,
        justifyContent:'space-between'
    },
    header:{
        padding:10,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },  
    title:{
        fontSize:24,
        fontFamily:'Ubuntu-BoldItalic',
        color:Colors.black,
    },
    questionNumberView:{
        paddingHorizontal:20,
        paddingVertical:8,
        backgroundColor:Colors.quesColor2,
        borderRadius:20,

    },
    questionNumber:{
        fontSize:16,
        fontFamily:'Ubuntu-Medium'
    },
    continueButtonView:{
        padding:10,
        backgroundColor:Colors.continueButtonColor,
        marginHorizontal:30,
        marginVertical:10
    },
    continueText:{
        color:Colors.white,
        textAlign:'center',
        fontSize:22,
        fontWeight:'900'  
    },
    questionContainer:{
        flex:1,
        justifyContent:'space-evenly',
        alignItems:'center'
    },
    question:{
        fontSize:28,
        fontFamily:'Ubuntu-BoldItalic',
        color:Colors.black
    },
    answerView:{
        height:60,
        width:350,
        backgroundColor:Colors.white,
        margin:10,
        elevation:5,
        shadowColor:Colors.black,
        shadowOffset:{
            width:5,
            height:5
        },
        borderRadius:30,
        alignItems:'center',
        justifyContent:'space-between',
        flexDirection:'row',
        paddingHorizontal:20

    },
    answersList:{
        textAlign:'center',
        fontSize:16,
        color:Colors.black

    },
    activeAnswerView:{
        backgroundColor:Colors.continueButtonColor
    },
    activeAnswerList:{
        color:Colors.white,
        fontSize:16,
        fontWeight:'900',
    },
    radioButton:{
        borderWidth:1,
        padding:5,
        borderRadius:20
    },
    activeButton:{
        borderColor:Colors.white
    },
    radioButtonInactive:{
        padding:8
    },
    activeradioButton:{
        padding:8,
        backgroundColor:Colors.white,
        borderRadius:10
    },
    genderContainer:{
        paddingVertical:30,
        width:350,
        flexDirection:"row",
        backgroundColor:Colors.sandal,
        borderRadius:20,
        justifyContent:'space-between',
        paddingRight:30
    },
    activegenderContainer:{
        borderWidth:1,
        elevation:5,
        shadowColor:Colors.black,
        shadowOffset:{
            width:10,
            height:10
        }
    },
    iconConatiner:{
        justifyContent:'space-between',
        alignItems:'center'
    },
    genderText:{
        fontSize:18,
        fontFamily:'Ubuntu-Medium',
        color:Colors.black
    }
})